=== rbuegar/UD.4/Act 4/Clientes/BDgestoria.dtd
<!ELEMENT gestoria (sede+)>
<!ELEMENT sede (cliente+)>
<!ELEMENT cliente (codigo_cliente, descripcion_cliente?, num_viviendas, coste_vivienda, resumen_viviendas, plazo_alta_hacienda)>
<!ELEMENT codigo_cliente (#PCDATA)>
<!ELEMENT descripcion_cliente (#PCDATA)>
<!ELEMENT num_viviendas (#PCDATA)>
<!ELEMENT coste_vivienda (#PCDATA)>
<!ELEMENT resumen_viviendas (#PCDATA)>
<!ELEMENT plazo_alta_hacienda (#PCDATA)>
<!ATTLIST sede
    codigo_sede CDATA #REQUIRED
    nombre_empleado CDATA #REQUIRED
    fecha_alta CDATA #REQUIRED>

=== rbuegar/UD.4/Act 4/Clientes/clientes.xml
<!DOCTYPE gestoria SYSTEM "BDgestoria.dtd">
<gestoria>
  <sede codigo_sede="S001" nombre_empleado="Juan" fecha_alta="2024-01-25">
    <cliente>
      <codigo_cliente>ABC-123</codigo_cliente>
      <descripcion_cliente>solvente</descripcion_cliente>
      <num_viviendas>3</num_viviendas>
      <coste_vivienda>150000.00</coste_vivienda>
      <resumen_viviendas>Resumen de las viviendas</resumen_viviendas>
      <plazo_alta_hacienda>2024-02-01</plazo_alta_hacienda>
    </cliente>
  </sede>
</gestoria>
