=== rbuegar/UD.4/Act 4/Mejora/futbol.dtd
<!ELEMENT futbol (equipo+)>
<!ELEMENT equipo (jugador+)>
<!ELEMENT jugador (codigo_jugador, nombre, posicion, salario)>
<!ELEMENT codigo_jugador (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT salario (#PCDATA)>
<!ATTLIST equipo
    codigo_equipo CDATA #REQUIRED
    nombre_entrenador CDATA #REQUIRED
    fecha_creacion CDATA #REQUIRED>

=== rbuegar/UD.4/Act 4/Mejora/equipo.xml
<!DOCTYPE futbol SYSTEM "futbol.dtd">
<futbol>
  <equipo codigo_equipo="E001" nombre_entrenador="Pep Guardiola" fecha_creacion="2024-01-25">
    <jugador>
      <codigo_jugador>PLR-001</codigo_jugador>
      <nombre>Lionel Messi</nombre>
      <posicion>Delantero</posicion>
      <salario>15000000.00</salario>
    </jugador>
    <jugador>
      <codigo_jugador>PLR-002</codigo_jugador>
      <nombre>Kevin De Bruyne</nombre>
      <posicion>Centrocampista</posicion>
      <salario>12000000.00</salario>
    </jugador>
  </equipo>
</futbol>
